"""initial_migration_complete_database_structure

Revision ID: d6825691d7a1
Revises: 
Create Date: 2025-07-17 05:29:21.171974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6825691d7a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mahasiswa',
    sa.Column('nim', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('program_studi', sa.String(length=50), nullable=False),
    sa.Column('ipk', sa.Float(), nullable=False),
    sa.Column('sks', sa.Integer(), nullable=False),
    sa.Column('persen_dek', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('nim')
    )
    op.create_table('saw_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_cost', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saw_criteria_id'), 'saw_criteria', ['id'], unique=False)
    op.create_table('klasifikasi_kelulusan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nim', sa.String(length=20), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=False),
    sa.Column('nilai_fuzzy', sa.Float(), nullable=False),
    sa.Column('ipk_membership', sa.Float(), nullable=False),
    sa.Column('sks_membership', sa.Float(), nullable=False),
    sa.Column('nilai_dk_membership', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nim'], ['mahasiswa.nim'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nim')
    )
    op.create_table('nilai',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nim', sa.String(length=20), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('kode_matakuliah', sa.String(length=20), nullable=False),
    sa.Column('nama_matakuliah', sa.String(length=100), nullable=False),
    sa.Column('nilai', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nim'], ['mahasiswa.nim'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saw_final_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nim', sa.String(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nim'], ['mahasiswa.nim'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saw_final_results_id'), 'saw_final_results', ['id'], unique=False)
    op.create_table('saw_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nim', sa.String(), nullable=False),
    sa.Column('nilai_akhir', sa.Float(), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nim'], ['mahasiswa.nim'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saw_results_id'), 'saw_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saw_results_id'), table_name='saw_results')
    op.drop_table('saw_results')
    op.drop_index(op.f('ix_saw_final_results_id'), table_name='saw_final_results')
    op.drop_table('saw_final_results')
    op.drop_table('nilai')
    op.drop_table('klasifikasi_kelulusan')
    op.drop_index(op.f('ix_saw_criteria_id'), table_name='saw_criteria')
    op.drop_table('saw_criteria')
    op.drop_table('mahasiswa')
    # ### end Alembic commands ### 